.macos_saas_runners:
  tags:
    - shared-macos-amd64
  image: macos-12-xcode-13

stages:
  - unit_tests
  - test_flight

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - gem install bundler
  - bundle install

unit_tests:
  extends:
    - .macos_saas_runners
  stage: unit_tests
  script:
    - bundle exec fastlane tests
  tags:
    - ios

test_flight_build:
  stage: test_flight
  script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # - fastlane beta
  tags:
    - ios
  only:
     - /^release-.*$/
     - main
