# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(
      scheme: "PipelineDemo",
      derived_data_path: "~/Library/Developer/Xcode/DerivedData",
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    setup_ci
    sync_code_signing(readonly: true)
    build_app(
      scheme: "PipelineDemo",
      export_method: "app-store",
    )
    app_store_connect_api_key(
      is_key_content_base64: true,
      duration: 1200,
    )
  end
end
